require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RedditNewsItemsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RedditNewsItem. As you add validations to RedditNewsItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RedditNewsItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all reddit_news_items as @reddit_news_items" do
      reddit_news_item = RedditNewsItem.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:reddit_news_items)).to eq([reddit_news_item])
    end
  end

  describe "GET #show" do
    it "assigns the requested reddit_news_item as @reddit_news_item" do
      reddit_news_item = RedditNewsItem.create! valid_attributes
      get :show, params: {id: reddit_news_item.to_param}, session: valid_session
      expect(assigns(:reddit_news_item)).to eq(reddit_news_item)
    end
  end

  describe "GET #new" do
    it "assigns a new reddit_news_item as @reddit_news_item" do
      get :new, params: {}, session: valid_session
      expect(assigns(:reddit_news_item)).to be_a_new(RedditNewsItem)
    end
  end

  describe "GET #edit" do
    it "assigns the requested reddit_news_item as @reddit_news_item" do
      reddit_news_item = RedditNewsItem.create! valid_attributes
      get :edit, params: {id: reddit_news_item.to_param}, session: valid_session
      expect(assigns(:reddit_news_item)).to eq(reddit_news_item)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RedditNewsItem" do
        expect {
          post :create, params: {reddit_news_item: valid_attributes}, session: valid_session
        }.to change(RedditNewsItem, :count).by(1)
      end

      it "assigns a newly created reddit_news_item as @reddit_news_item" do
        post :create, params: {reddit_news_item: valid_attributes}, session: valid_session
        expect(assigns(:reddit_news_item)).to be_a(RedditNewsItem)
        expect(assigns(:reddit_news_item)).to be_persisted
      end

      it "redirects to the created reddit_news_item" do
        post :create, params: {reddit_news_item: valid_attributes}, session: valid_session
        expect(response).to redirect_to(RedditNewsItem.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved reddit_news_item as @reddit_news_item" do
        post :create, params: {reddit_news_item: invalid_attributes}, session: valid_session
        expect(assigns(:reddit_news_item)).to be_a_new(RedditNewsItem)
      end

      it "re-renders the 'new' template" do
        post :create, params: {reddit_news_item: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reddit_news_item" do
        reddit_news_item = RedditNewsItem.create! valid_attributes
        put :update, params: {id: reddit_news_item.to_param, reddit_news_item: new_attributes}, session: valid_session
        reddit_news_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested reddit_news_item as @reddit_news_item" do
        reddit_news_item = RedditNewsItem.create! valid_attributes
        put :update, params: {id: reddit_news_item.to_param, reddit_news_item: valid_attributes}, session: valid_session
        expect(assigns(:reddit_news_item)).to eq(reddit_news_item)
      end

      it "redirects to the reddit_news_item" do
        reddit_news_item = RedditNewsItem.create! valid_attributes
        put :update, params: {id: reddit_news_item.to_param, reddit_news_item: valid_attributes}, session: valid_session
        expect(response).to redirect_to(reddit_news_item)
      end
    end

    context "with invalid params" do
      it "assigns the reddit_news_item as @reddit_news_item" do
        reddit_news_item = RedditNewsItem.create! valid_attributes
        put :update, params: {id: reddit_news_item.to_param, reddit_news_item: invalid_attributes}, session: valid_session
        expect(assigns(:reddit_news_item)).to eq(reddit_news_item)
      end

      it "re-renders the 'edit' template" do
        reddit_news_item = RedditNewsItem.create! valid_attributes
        put :update, params: {id: reddit_news_item.to_param, reddit_news_item: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested reddit_news_item" do
      reddit_news_item = RedditNewsItem.create! valid_attributes
      expect {
        delete :destroy, params: {id: reddit_news_item.to_param}, session: valid_session
      }.to change(RedditNewsItem, :count).by(-1)
    end

    it "redirects to the reddit_news_items list" do
      reddit_news_item = RedditNewsItem.create! valid_attributes
      delete :destroy, params: {id: reddit_news_item.to_param}, session: valid_session
      expect(response).to redirect_to(reddit_news_items_url)
    end
  end

end
